name: Test h34vvy_u53rzz

on:
  pull_request:
    branches:
      - main
    paths:
      - "h34vvy_u53rzz/**"
      - ".github/workflows/h34vvy_u53rzz.yaml"
      - ".github/workflows/reusable_team_ci.yaml"
jobs:
  call-workflow:
    uses: ./.github/workflows/reusable_team_ci.yaml
    with:
      target_app: "h34vvy_u53rzz"